In [1]:
!unzip '/content/drive/MyDrive/birds.zip'

Archive:  /content/drive/MyDrive/birds.zip
  inflating: test_data/test_data/blasti/DSC_6396.jpg  
  inflating: test_data/test_data/blasti/DSC_6397.jpg  
  inflating: test_data/test_data/blasti/DSC_6398.jpg  
  inflating: test_data/test_data/blasti/DSC_6399.jpg  
  inflating: test_data/test_data/blasti/DSC_6400.jpg  
  inflating: test_data/test_data/blasti/DSC_6401.jpg  
  inflating: test_data/test_data/blasti/DSC_6402.jpg  
  inflating: test_data/test_data/blasti/DSC_6403.jpg  
  inflating: test_data/test_data/blasti/DSC_6405.jpg  
  inflating: test_data/test_data/blasti/DSC_6406.jpg  
  inflating: test_data/test_data/blasti/DSC_6407.jpg  
  inflating: test_data/test_data/blasti/DSC_6408.jpg  
  inflating: test_data/test_data/blasti/DSC_6409.jpg  
  inflating: test_data/test_data/blasti/DSC_6410.jpg  
  inflating: test_data/test_data/blasti/DSC_6411.jpg  
  inflating: test_data/test_data/bonegl/DSC_4587.jpg  
  inflating: test_data/test_data/bonegl/DSC_4588.jpg  
  inflating: test_data

In [ ]:
#Data augmentation

In [2]:
from tensorflow.keras.preprocessing.image import ImageDataGenerator

In [3]:
train_gen = ImageDataGenerator(rescale=(1./255),horizontal_flip=True,shear_range=0.2)
test_gen = ImageDataGenerator(rescale=(1./255))

In [4]:
train = train_gen.flow_from_directory('/content/train_data/train_data',
                                      target_size=(120,120),
                                      class_mode='categorical',
                                      batch_size=8
                                      )
test = test_gen.flow_from_directory('/content/test_data/test_data',
                                     target_size=(120,120),
                                     class_mode='categorical',
                                     batch_size=8
                                     )

Found 150 images belonging to 16 classes.
Found 157 images belonging to 16 classes.


In [5]:
train.class_indices

{'blasti': 0,
 'bonegl': 1,
 'brhkyt': 2,
 'cbrtsh': 3,
 'cmnmyn': 4,
 'gretit': 5,
 'hilpig': 6,
 'himbul': 7,
 'himgri': 8,
 'hsparo': 9,
 'indvul': 10,
 'jglowl': 11,
 'lbicrw': 12,
 'mgprob': 13,
 'rebimg': 14,
 'wcrsrt': 15}

In [6]:
#CNN Model
from tensorflow.keras.layers import Convolution2D,MaxPooling2D,Flatten,Dense
from tensorflow.keras.models import Sequential

In [ ]:
model = Sequential()
model.add(Convolution2D(20,(3,3),activation='relu',input_shape=(120,120,3)))
model.add(MaxPooling2D(pool_size=(2,2)))
model.add(Flatten())
model.add(Dense(45,activation='relu'))
model.add(Dense(16,activation='softmax'))

In [ ]:
model.compile(optimizer='adam',loss='categorical_crossentropy',metrics=['accuracy'])

In [ ]:
model.fit(train,batch_size=8,validation_data=test,epochs=10)

Epoch 1/10
19/19 [==============================] - 130s 7s/step - loss: 4.0066 - accuracy: 0.1067 - val_loss: 2.7499 - val_accuracy: 0.1465
Epoch 2/10
19/19 [==============================] - 80s 4s/step - loss: 2.6417 - accuracy: 0.1267 - val_loss: 2.7652 - val_accuracy: 0.0764
Epoch 3/10
19/19 [==============================] - 82s 4s/step - loss: 2.5655 - accuracy: 0.2000 - val_loss: 2.8046 - val_accuracy: 0.0573
Epoch 4/10
19/19 [==============================] - 80s 4s/step - loss: 2.4829 - accuracy: 0.1933 - val_loss: 2.8533 - val_accuracy: 0.1210
Epoch 5/10
19/19 [==============================] - 116s 6s/step - loss: 2.4970 - accuracy: 0.1933 - val_loss: 2.7781 - val_accuracy: 0.1338
Epoch 6/10
19/19 [==============================] - 82s 4s/step - loss: 2.3477 - accuracy: 0.2267 - val_loss: 2.7454 - val_accuracy: 0.1720
Epoch 7/10
19/19 [==============================] - 84s 5s/step - loss: 2.2403 - accuracy: 0.2600 - val_loss: 2.6981 - val_accuracy: 0.1465
Epoch 8/10
19/19 [

In [ ]:
model.save('birdWeights.h5')

In [ ]:
#Testing

In [ ]:
import numpy as np
from tensorflow.keras.preprocessing import image

In [ ]:
img = image.load_img('/content/crow.jpg', target_size=(120,120))

In [ ]:
img = image.img_to_array(img)
img 

array([[[126., 110.,  87.],
        [116., 100.,  77.],
        [110.,  94.,  71.],
        ...,
        [116.,  99.,  79.],
        [120., 104.,  81.],
        [114.,  97.,  77.]],

       [[134., 120.,  94.],
        [119., 103.,  78.],
        [114., 100.,  74.],
        ...,
        [123., 105.,  83.],
        [119., 103.,  80.],
        [113.,  96.,  78.]],

       [[132., 117.,  94.],
        [117., 102.,  79.],
        [115., 100.,  81.],
        ...,
        [123., 106.,  80.],
        [110.,  93.,  73.],
        [108.,  93.,  74.]],

       ...,

       [[230., 230., 230.],
        [236., 236., 236.],
        [231., 229., 230.],
        ...,
        [ 96.,  97.,  39.],
        [ 69., 103.,  17.],
        [ 71.,  89.,  27.]],

       [[229., 229., 227.],
        [232., 231., 229.],
        [228., 228., 226.],
        ...,
        [ 87.,  81.,  29.],
        [ 74., 121.,  19.],
        [ 52.,  37.,   8.]],

       [[233., 233., 233.],
        [230., 230., 230.],
        [231., 2

In [ ]:
img=np.expand_dims(img,axis=0)
img

array([[[[126., 110.,  87.],
         [116., 100.,  77.],
         [110.,  94.,  71.],
         ...,
         [116.,  99.,  79.],
         [120., 104.,  81.],
         [114.,  97.,  77.]],

        [[134., 120.,  94.],
         [119., 103.,  78.],
         [114., 100.,  74.],
         ...,
         [123., 105.,  83.],
         [119., 103.,  80.],
         [113.,  96.,  78.]],

        [[132., 117.,  94.],
         [117., 102.,  79.],
         [115., 100.,  81.],
         ...,
         [123., 106.,  80.],
         [110.,  93.,  73.],
         [108.,  93.,  74.]],

        ...,

        [[230., 230., 230.],
         [236., 236., 236.],
         [231., 229., 230.],
         ...,
         [ 96.,  97.,  39.],
         [ 69., 103.,  17.],
         [ 71.,  89.,  27.]],

        [[229., 229., 227.],
         [232., 231., 229.],
         [228., 228., 226.],
         ...,
         [ 87.,  81.,  29.],
         [ 74., 121.,  19.],
         [ 52.,  37.,   8.]],

        [[233., 233., 233.],
       

In [ ]:
model.predict(img)

1/1 [==============================] - 0s 116ms/step


array([[0.0000000e+00, 0.0000000e+00, 0.0000000e+00, 0.0000000e+00,
        0.0000000e+00, 0.0000000e+00, 0.0000000e+00, 0.0000000e+00,
        0.0000000e+00, 0.0000000e+00, 0.0000000e+00, 0.0000000e+00,
        1.0000000e+00, 0.0000000e+00, 0.0000000e+00, 2.7052346e-17]],
      dtype=float32)

In [ ]:
np.argmax(model.predict(img))

1/1 [==============================] - 0s 17ms/step


12

In [ ]:
# Testing 1
img1 = image.load_img('/content/owl.jpg',target_size=(120,120))
img1 = image.img_to_array(img1)
img1 = np.expand_dims(img1,axis=0)
pred = np.argmax(model.predict(img1))
print(pred)

1/1 [==============================] - 0s 33ms/step
3


In [ ]:
# Testing 2
img2 = image.load_img('/content/crow.jpg',target_size=(120,120))
img2 = image.img_to_array(img2)
img2 = np.expand_dims(img2,axis=0)
pred = np.argmax(model.predict(img2))
print(pred)

1/1 [==============================] - 0s 17ms/step
12


In [ ]:
# Testing 3
img3 = image.load_img('/content/pigeon.jpg',target_size=(120,120))
img3 = image.img_to_array(img3)
img3 = np.expand_dims(img3,axis=0)
pred = np.argmax(model.predict(img3))
print(pred)

1/1 [==============================] - 0s 17ms/step
3


In [ ]:
# Model Tuning (Adding feature extraction layers)

In [ ]:
model = Sequential()
model.add(Convolution2D(12,(3,3),activation='relu',input_shape=(120, 120, 3)))
model.add(MaxPooling2D(pool_size=(2,2)))
model.add(Convolution2D(24,(3,3),activation='relu'))
model.add(MaxPooling2D(pool_size=(2,2)))
model.add(Convolution2D(36,(3,3),activation='relu'))
model.add(MaxPooling2D(pool_size=(2,2)))
model.add(Flatten())
model.add(Dense(62,activation='relu'))
model.add(Dense(32,activation='relu'))
model.add(Dense(16,activation='relu'))
model.add(Dense(16,activation='softmax'))

In [ ]:
model.summary()

Model: "sequential_2"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 conv2d_4 (Conv2D)           (None, 118, 118, 12)      336       
                                                                 
 max_pooling2d_4 (MaxPooling  (None, 59, 59, 12)       0         
 2D)                                                             
                                                                 
 conv2d_5 (Conv2D)           (None, 57, 57, 24)        2616      
                                                                 
 max_pooling2d_5 (MaxPooling  (None, 28, 28, 24)       0         
 2D)                                                             
                                                                 
 conv2d_6 (Conv2D)           (None, 26, 26, 36)        7812      
                                                                 
 max_pooling2d_6 (MaxPooling  (None, 13, 13, 36)      

In [ ]:
model.compile(optimizer='adam',loss='categorical_crossentropy',metrics=['accuracy'])

In [ ]:
model.fit(train,batch_size=8,validation_data=test,epochs=50)

Epoch 1/50
19/19 [==============================] - 87s 5s/step - loss: 2.7799 - accuracy: 0.0800 - val_loss: 2.7682 - val_accuracy: 0.1083
Epoch 2/50
19/19 [==============================] - 118s 6s/step - loss: 2.7636 - accuracy: 0.1133 - val_loss: 2.7441 - val_accuracy: 0.1338
Epoch 3/50
19/19 [==============================] - 82s 4s/step - loss: 2.7311 - accuracy: 0.1600 - val_loss: 2.7243 - val_accuracy: 0.1210
Epoch 4/50
19/19 [==============================] - 85s 5s/step - loss: 2.6094 - accuracy: 0.2067 - val_loss: 2.6892 - val_accuracy: 0.1529
Epoch 5/50
19/19 [==============================] - 83s 5s/step - loss: 2.6627 - accuracy: 0.1600 - val_loss: 2.6904 - val_accuracy: 0.1338
Epoch 6/50
19/19 [==============================] - 82s 4s/step - loss: 2.4893 - accuracy: 0.1933 - val_loss: 2.6784 - val_accuracy: 0.1656
Epoch 7/50
19/19 [==============================] - 83s 5s/step - loss: 2.4048 - accuracy: 0.2000 - val_loss: 2.7172 - val_accuracy: 0.1401
Epoch 8/50
19/19 [=

In [ ]:
# Testing 1
img1 = image.load_img('/content/owl.jpg',target_size=(120,120))
img1 = image.img_to_array(img1)
img1 = np.expand_dims(img1,axis=0)
pred = np.argmax(model.predict(img1))
print(pred)

1/1 [==============================] - 0s 153ms/step
14


In [ ]:
# Testing 2
img2 = image.load_img('/content/crow.jpg',target_size=(120,120))
img2 = image.img_to_array(img2)
img2 = np.expand_dims(img2,axis=0)
pred = np.argmax(model.predict(img2))
print(pred)


1/1 [==============================] - 0s 18ms/step
14


In [ ]:
# Testing 3
img3 = image.load_img('/content/pigeon.jpg',target_size=(120,120))
img3 = image.img_to_array(img3)
img3 = np.expand_dims(img3,axis=0)
pred = np.argmax(model.predict(img3))
print(pred)


1/1 [==============================] - 0s 17ms/step
7


In [ ]:
# Model tuning (with dropout, batch normalization & early stopping)

In [7]:
from tensorflow.keras.layers import BatchNormalization, Dropout

In [8]:
model = Sequential()
model.add(Convolution2D(12,(3,3),activation='relu',input_shape=(120, 120, 3)))
model.add(BatchNormalization())
model.add(MaxPooling2D(pool_size=(2,2)))
model.add(Dropout(0.2))
model.add(Convolution2D(24,(3,3),activation='relu'))
model.add(BatchNormalization())
model.add(MaxPooling2D(pool_size=(2,2)))
model.add(Dropout(0.2))
model.add(Convolution2D(36,(3,3),activation='relu'))
model.add(BatchNormalization())
model.add(MaxPooling2D(pool_size=(2,2)))
model.add(Dropout(0.2))
model.add(Flatten())
model.add(Dense(62,activation='relu'))
model.add(BatchNormalization())
model.add(Dropout(0.1))
model.add(Dense(32,activation='relu'))
model.add(Dense(16,activation='relu'))
model.add(Dense(16,activation='softmax'))

In [9]:
model.summary()  

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 conv2d (Conv2D)             (None, 118, 118, 12)      336       
                                                                 
 batch_normalization (BatchN  (None, 118, 118, 12)     48        
 ormalization)                                                   
                                                                 
 max_pooling2d (MaxPooling2D  (None, 59, 59, 12)       0         
 )                                                               
                                                                 
 dropout (Dropout)           (None, 59, 59, 12)        0         
                                                                 
 conv2d_1 (Conv2D)           (None, 57, 57, 24)        2616      
                                                                 
 batch_normalization_1 (Batc  (None, 57, 57, 24)       9

In [10]:
model.compile(optimizer='adam',loss='categorical_crossentropy',metrics=['accuracy'])

In [11]:
from tensorflow.keras.callbacks import EarlyStopping

In [12]:
early_stop = EarlyStopping(monitor='accuracy',patience=8)

In [1]:
model.fit(train,batch_size=8,validation_data=test,epochs=50,callbacks=early_stop)

NameError: ignored

In [ ]:
# Testing 1
img1 = image.load_img('/content/owl.jpg',target_size=(120,120))
img1 = image.img_to_array(img1)
img1 = np.expand_dims(img1,axis=0)
pred = np.argmax(model.predict(img1))
print(pred)

In [ ]:
# Testing 2
img2 = image.load_img('/content/crow.jpg',target_size=(120,120))
img2 = image.img_to_array(img2)
img2 = np.expand_dims(img2,axis=0)
pred = np.argmax(model.predict(img2))
print(pred)

In [ ]:
# Testing 3
img3 = image.load_img('/content/pigeon.jpg',target_size=(120,120))
img3 = image.img_to_array(img3)
img3 = np.expand_dims(img3,axis=0)
pred = np.argmax(model.predict(img3))
print(pred)